stages:
  - deploy
  
pages:
  stage: deploy
  image: python:3.8-alpine
  before_script:
    - apk update && apk add make
    - python -m pip install -r requirements.txt
    - python -m pip install sphinx sphinx-rtd-theme
  script:
    - cd docs && make clean html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public

